version: "3.8"

services:
    discovery-service:
        build:
            context: .
            dockerfile: ./DiscoveryService/Dockerfile
        ports:
            - "8761:8761"
        healthcheck:
          test: ["CMD", "curl", "-f", "http://discovery-service:8761"]
          interval: 5s
          timeout: 3s
          retries: 7
    getway-service:
        build:
            context: .
            dockerfile: ./GetwayService/Dockerfile
        ports: 
            - "8080:8080"
        depends_on:
            - discovery-service
        restart: on-failure
        environment:
            EUREKA_SERVER: http://discovery-service:8761/eureka
    central-admin:
        build:
            context: .
            dockerfile: ./CentralAdmin/Dockerfile
        ports: 
            - "8083:8083"
        depends_on:
            - discovery-service
            - getway-service
        restart: on-failure
        environment:
            EUREKA_SERVER: http://discovery-service:8761/eureka
    customer:
        build:
            context: .
            dockerfile: ./Customer/Dockerfile
        ports: 
            - "8084:8084"
        depends_on:
            - discovery-service
            - getway-service
        restart: on-failure
        environment:
            EUREKA_SERVER: http://discovery-service:8761/eureka