version: "3.8"

services:
    discovery-service:
        image: discovery-service
        ports:
            - "8761:8761"
        healthcheck:
          test: ["CMD", "curl", "-f", "http://discovery-service:8761"]
          interval: 5s
          timeout: 3s
          retries: 7
    getway-service:
        image: getway-service
        ports: 
            - "8080:8080"
        depends_on:
            - discovery-service
        restart: on-failure
        environment:
            EUREKA_SERVER: http://discovery-service:8761/eureka
    central-admin:
        image: central-admin
        ports: 
            - "8083:8083"
        depends_on:
            - discovery-service
            - getway-service
        restart: on-failure
        environment:
            EUREKA_SERVER: http://discovery-service:8761/eureka
    customer:
        image: customer
        ports: 
            - "8084:8084"
        depends_on:
            - discovery-service
            - getway-service
        restart: on-failure
        environment:
            EUREKA_SERVER: http://discovery-service:8761/eureka
    auth-service:
        image: auth-service
        ports: 
            - "8082:8082"
        depends_on:
            - discovery-service
            - getway-service
        restart: on-failure
        environment:
            EUREKA_SERVER: http://discovery-service:8761/eureka
    export-service:
        image: export
        ports: 
            - "8081:8081"
        depends_on:
            - discovery-service
            - getway-service
        restart: on-failure
        environment:
            EUREKA_SERVER: http://discovery-service:8761/eureka
    swift-service:
        image: swift
        ports: 
            - "8085:8085"
        depends_on:
            - discovery-service
            - getway-service
        restart: on-failure
        environment:
            EUREKA_SERVER: http://discovery-service:8761/eureka