server:
  port: 8090

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO

spring:
  application:
    name: client-server
  security:
    oauth2:
      client:
        registration:
          bank-client-oidc:
            provider: spring
            client-id: bank-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8090/login/oauth2/code/{registrationId}"
            scope: openid
            client-name: bank-client-oidc
          bank-client-authorization-code:
            provider: spring
            client-id: bank-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8090/authorized"
            client-name: bank-client-authorization-code
        provider:
          spring:
            issuer-uri: http://auth-server:9000